### ISSUE TITLE
Default `ON DELETE RESTRICT` in MySQL schema causes trouble with JobRepositoryTestUtils

### ISSUE THREAD

**Issue by flozano** [spring-projects/spring-batch#4322] opened 2023-03-08 16:16 UTC
In MySQL schema:
https://github.com/spring-projects/spring-batch/blob/main/spring-batch-core/src/main/resources/org/springframework/batch/core/schema-mysql.sql

a FK is defined with default cascade behaviour (`ON DELETE RESTRICT`):
```sql
	constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
```

However, https://github.com/spring-projects/spring-batch/blob/main/spring-batch-test/src/main/java/org/springframework/batch/test/JobRepositoryTestUtils.java doesn't take care of cleaning the dependant rows, and a failure is caused when used:

```
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [DELETE FROM BATCH_JOB_EXECUTION WHERE JOB_EXECUTION_ID = ?]; Cannot delete or update a parent row: a foreign key constraint fails (`test`.`BATCH_STEP_EXECUTION`, CONSTRAINT `JOB_EXEC_STEP_FK` FOREIGN KEY (`JOB_EXECUTION_ID`) REFERENCES `BATCH_JOB_EXECUTION` (`JOB_EXECUTION_ID`))
```

**Comment by fmbenhassine** [comment] 2024-03-26 14:06
I am closing this issue as I believe it has been fixed in #4249 since v5.0.1. But if the problem is still present, please add a comment and we will reopen the issue for further investigation. Thank you.

**Closed by fmbenhassine** 2024-03-26 14:06 UTC
Labels: status: waiting-for-reporter, type: bug
