### ISSUE TITLE
Cannot run job with LocalDate(Time) job parameters

### ISSUE THREAD

**Issue by winfr34k** [spring-projects/spring-batch#4257] opened 2022-12-11 23:28 UTC
I didn't find any obvious duplicate but maybe I'm also misunderstanding the scopes of the Spring Batch project, so maybe this "bug" is really as designed.

**Bug description**

If a job is run with LocalDate or LocalDateTime job parameters, the run fails because the execution cannot be persisted.
An exception like "No converter found capable of converting from type [java.time.LocalDate] to type [java.lang.String]" is thrown.

**Environment**

* Spring Boot 3.0.0
* Spring Batch 5.0.0
* H2 Database 2.1.214
* OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
* macOS 13.0.1

**Steps to reproduce**

1. Prepare `JobParameters` using the `JobParametersBuilder` with either `LocalDate` or `LocalDateTime` instances.
2. Run any job with the aforementioned job parameters

**Expected behavior**

Since the builder offers convenience methods, I would expect the job execution to just complete with either of them.

**Minimal Complete Reproducible example**

https://gitlab.com/winfr34k/spring-batch-localdate-reproducer

**Comment by fmbenhassine** [comment] 2023-01-13 13:40
Thank you for raising this issue and for providing a sample.

The problem is that the default conversion service from Spring Framework that Spring Batch uses by default does not support the conversion of `String` literals to/from `LocalDate` and `LocalDateTime` OOTB.

The issue could be fixed by providing a conversion service that augments the default one with converters for `LocalDate` and `LocalDateTime`. But since the `JobParametersBuilder` provides methods to add job parameters with such types, I agree that those converters should be provided by default.

I will plan the fix for v5.0.1.

**Closed** 2023-02-15 22:57 UTC
Labels: type: bug, in: core
