### ISSUE TITLE
Fault tolerance in steps with a ChunkSize of 1 does not work

### ISSUE THREAD

**Issue by biggestmattyp** [spring-projects/spring-batch#4421] opened 2023-07-19 03:33 UTC
Please do a quick search on Github issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
The fault tolerance settings on a step with a chunksize of 1 do not work.  With a chunk size of 1, the whole step completes no matter what if there is an exception and fault tolerance is turned on for that exception (or any Exception.class)

**Environment**
Spring Batch 4.3.7, Java 1.8

**Steps to reproduce**
Create a job with a step, that has a chunksize of 1, and configure fault tolerance.  Then attempt to run this.

**Expected behavior**
I would expect the step to move onto the next chunk and attempt to process that (1 at a time with a chunk size of 1).

**Minimal Complete Reproducible example**
See above to reproduce.

**Comment by fmbenhassine** [comment] 2023-11-17 09:00
Fault-tolerance should work the same way no matter the chunk size. 

> Expected behavior
>I would expect the step to move onto the next chunk and attempt to process that (1 at a time with a chunk size of 1).

That is the case, here is a complete example:

```java
package com.example.gh4421;

import java.util.Arrays;

import org.springframework.batch.core.Job;
import org.springframework.batch.core.configuration.annotation.EnableBatchProcessing;
import org.springframework.batch.core.configuration.annotation.JobBuilderFactory;
import org.springframework.batch.core.configuration.annotation.StepBuilderFactory;
import org.springframework.batch.core.listener.SkipListenerSupport;
import org.springframework.batch.item.ItemProcessor;
import org.springframework.batch.item.support.ListItemReader;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
@EnableBatchProcessing
public class Gh4421Application {

	public static void main(String[] args) {
		SpringApplication.run(Gh4421Application.class, args);
	}

	@Bean
	public Job job(JobBuilderFactory jobs, StepBuilderFactory steps) {
		return jobs.get("job")
				.start(steps.get("step")
						.<Integer, Integer>chunk(1)
						.reader(new ListItemReader<>(Arrays.asList(0, 1, 2, 3)))
						.processor((ItemProcessor<Integer, Integer>) item -> {
							System.out.println("Processing item " + item);
							if (item % 2 != 0) {
								throw new InvalidItemException("Invalid odd item " + item);
							}
							return item;
						})
						.writer(items -> items.forEach(System.out::println))
						.faultTolerant()
						.retry(InvalidItemException.class)
						.retryLimit(3)
						.skip(InvalidItemException.class)
						.skipLimit(10)
						.listener(new InvalidItemSkipListener())
						.build())
				.build();
	}

	static class InvalidItemException extends Exception {
		public InvalidItemException(String message) {
			super(message);
		}
	}

	static class InvalidItemSkipListener extends SkipListenerSupport<Integer, Integer> {
		@Override
		public void onSkipInProcess(Integer integer, Throwable throwable) {
			System.err.println("Skipping item " + integer);
		}
	}

}
```

This prints:


```
2023-11-17 09:41:50.017  INFO 73265 --- [           main] com.example.gh4421.Gh4421Application     : Starting Gh4421Application using Java 1.8.0_292 on xxx with PID 73265
2023-11-17 09:41:50.019  INFO 73265 --- [           main] com.example.gh4421.Gh4421Application     : No active profile set, falling back to 1 default profile: "default"
2023-11-17 09:41:50.449  INFO 73265 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2023-11-17 09:41:50.605  INFO 73265 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2023-11-17 09:41:50.748  INFO 73265 --- [           main] o.s.b.c.r.s.JobRepositoryFactoryBean     : No database type set, using meta data indicating: H2
2023-11-17 09:41:50.858  INFO 73265 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : No TaskExecutor has been set, defaulting to synchronous executor.
2023-11-17 09:41:50.924  INFO 73265 --- [           main] com.example.gh4421.Gh4421Application     : Started Gh4421Application in 1.138 seconds (JVM running for 1.572)
2023-11-17 09:41:50.925  INFO 73265 --- [           main] o.s.b.a.b.JobLauncherApplicationRunner   : Running default command line with: []
2023-11-17 09:41:50.959  INFO 73265 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=job]] launched with the following parameters: [{}]
2023-11-17 09:41:50.985  INFO 73265 --- [           main] o.s.batch.core.job.SimpleStepHandler     : Executing step: [step]
Processing item 0
0
Processing item 1
Processing item 1
Processing item 1
Processing item 2
2
Processing item 3
Processing item 3
Processing item 3
2023-11-17 09:41:51.007  INFO 73265 --- [           main] o.s.batch.core.step.AbstractStep         : Step: [step] executed in 21ms
2023-11-17 09:41:51.009  INFO 73265 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=job]] completed with the following parameters: [{}] and the following status: [COMPLETED] in 36ms
Skipping item 1
Skipping item 3
2023-11-17 09:41:51.012  INFO 73265 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2023-11-17 09:41:51.014  INFO 73265 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

So even with a chunk size = 1, items are retried and skipped as expected (tested as reported with Spring Batch 4.3.7 and Java 1.8). If you change the skip limit to 1, the step fails as expected with `Skip limit of '1' exceeded`.

I am closing this issue for now as I am not able to reproduce it, but if you manage to provide a [minimal complete example](https://github.com/spring-projects/spring-batch/blob/main/ISSUE_REPORTING.md) that reproduces your specific issue, then i will re-open this ticket for further investigation. Thank you.


---

[gh4421.zip](https://github.com/spring-projects/spring-batch/files/13389523/gh4421.zip)

**Closed by fmbenhassine** 2023-11-17 09:00 UTC
Labels: status: waiting-for-triage, type: bug
