### ISSUE TITLE
Next state not found in flow='xyz' for state=abc.stepx with exit status=ABC_EFJ - FlowExecutionException

### ISSUE THREAD

**Issue by AJ198081** [spring-projects/spring-batch#4348] opened 2023-04-11 11:28 UTC
**Bug description**
The exception is thrown in all cases where the flow follow a path 'from().on().to()', for anything else it works

**Environment**
Java 17, Srping-boot 3.0.5, Spring-batch 5

**Steps to reproduce**
1. Create a Job, that controls the flow based on step's ExitStatus code, 
``` public Job prepareFlowers() {
        return new JobBuilder("prepareFlowersJob", jobRepository)
                .start(selectFlowersStep())
                .on(FlowerSelectionStepExecutionListener.NO_TRIM_REQUIRED).to(arrangeFlowersStep())
                .from(selectFlowersStep()).on(FlowerSelectionStepExecutionListener.TRIM_REQUIRED).to(removeThornsStep())
                .from(removeThornsStep()).next(arrangeFlowersStep())
                .end()
                .build();
```

I have added the photos of the 'stateTransitions' list from SimpleFlow.java in debug mode which show that the there is no transition from step0 (selectFlowerStep()) when 'Trim Required', 
in fact it shows the transition from step2 when 'Trim Required', it appears that 'from()' doesn't create the transition from 'selectFlowersStep()' but instead creates a new Step altogether.

Hopefully the images will be uploaded properly, doesn't look like.. If [photos don't upload please have a look at this Issue, I have added there earlier today.
](https://github.com/spring-projects/spring-batch/issues/4328)

![image](https://user-images.githubusercontent.com/77644260/231146497-7cbff1e3-14b7-487f-8a4f-5b22a83d0c0d.png)

Here is the [link to my project ](https://github.com/AJ198081/spring-batch/blob/master/src/main/java/dev/aj/springbatch/config/jobs/BatchJob.java

**Expected behavior**
The job flow should execute for all control paths

**Minimal Complete Reproducible example**
The code throws the next State not found - FlowExecutionException
![image](https://user-images.githubusercontent.com/77644260/231149872-cf1f92bc-304d-4764-8af7-e4aa5b4bcdbd.png)

![image](https://user-images.githubusercontent.com/77644260/231149951-1de8e235-302a-4a3a-ba69-15554d58a883.png)

![image](https://user-images.githubusercontent.com/77644260/231300092-67e1c64c-2d9b-490c-b80f-e8caea2e4eab.png)

Successful execution - when step1() ExitCode is 'Rose' -
![image](https://user-images.githubusercontent.com/77644260/231300202-34bae6db-46f4-408b-a0ff-06c1e88a2fb1.png)

FlowExecutionException - when step1 ExitCode is 'Lotus' - 
![image](https://user-images.githubusercontent.com/77644260/231300467-19f788da-8395-4737-8006-367279d2402c.png)

**Comment by fmbenhassine** [comment] 2023-04-11 13:13
Thank you for opening this issue. I edited your comment to fix formatting, now the screenshots are correctly rendered.

> If photos don't upload please have a look at this Issue, I have added there earlier today

However, is this the same issue as #4328? If yes, please close this one.

Otherwise, please provide a minimal example that we can run to reproduce the issue as mentioned in the [Issue reporting guide](https://github.com/spring-projects/spring-batch#reporting-issues). Thank you.

**Comment by AJ198081** [comment] 2023-04-11 22:09
Thanks Mahmoud,

Here is a minimal code that will help you replicate the issue, run the job a couple of times, if the Exit Status of step1() is 'Rose' then it will execute but if it is 'Lotus' then will throw FlowExecutionException.

```@Component
@RequiredArgsConstructor
@Slf4j
public class SpringBatchErrorDemo {
    private final JobRepository jobRepository;
    private final PlatformTransactionManager transactionManager;
    @Bean("springBatchError")
    public Job getJob() {
        return new JobBuilder("batchJobDemo", jobRepository)
                .incrementer(new RunIdIncrementer())
                .start(step1())
                .on("Rose").to(step2())
                .from(step1()).on("Lotus").to(step3())
                .end().build();
    }
    private Step step3() {
        return new StepBuilder("step2", jobRepository)
                .tasklet(((contribution, chunkContext) -> {
                    log.info("Executing Step " + contribution.getStepExecution().getStepName().toUpperCase());
                    return RepeatStatus.FINISHED;
                }), transactionManager)
                .build();
    }
    private Step step2() {
        return new StepBuilder("step3", jobRepository)
                .tasklet(((contribution, chunkContext) -> {
                    log.info("Executing Step " + contribution.getStepExecution().getStepName().toUpperCase());
                    return RepeatStatus.FINISHED;
                }), transactionManager)
                .build();
    }
    private Step step1() {
        return new StepBuilder("step1", jobRepository)
                .tasklet(((contribution, chunkContext) -> {
                    log.info("Executing step 1");
                    return RepeatStatus.FINISHED;
                }), transactionManager)
                .listener(new StepExec())
                .build();
    }
    static class StepExec implements StepExecutionListener {
        @Override
        public void beforeStep(StepExecution stepExecution) {
            log.info(String.format("Executing before Step Logic for %s", stepExecution.getStepName().toUpperCase()));
        }
        @Override
        public ExitStatus afterStep(StepExecution stepExecution) {
            String exitCode = new Random().nextBoolean() ? "Rose" : "Lotus";
            ExitStatus exitStatus = new ExitStatus(exitCode);
            log.info(String.format("Exit Status of %s is %s", stepExecution.getStepName().toUpperCase(), exitStatus.getExitCode()));
            return exitStatus;
        }
    }
}

![image](https://user-images.githubusercontent.com/77644260/231298399-36061693-3cf7-450e-ac3c-7ff3f5082dfd.png)

Screenshots of the Exception - 
![image](https://user-images.githubusercontent.com/77644260/231298778-004cd8b0-7bbf-4267-bf31-901477523096.png)

Screenshot of successful job execution - 
![image](https://user-images.githubusercontent.com/77644260/231299033-99108666-5ec8-42b4-b1e7-bc6c98a4ea7e.png)

**Comment by acktsap** [comment] 2023-04-13 03:43
Hi, it looks because you are using method to create the `step1`. Spring batch seems to recognize as another step when executing following code (i'm not sure it's indented behavior) 

```java
    @Bean("springBatchError")
    public Job getJob() {
        return new JobBuilder("batchJobDemo", jobRepository)
                .incrementer(new RunIdIncrementer())
                .start(step1()).on("Rose").to(step2())
                .from(step1()).on("Lotus").to(step3()) // another step named 'step1' 
                .end().build();
    }
```

Maybe your code can be fixed by using singleton bean when creating `step1`

```java
@RequiredArgsConstructor
@Slf4j
public class SpringBatchErrorDemo {
    private final JobRepository jobRepository;
    private final PlatformTransactionManager transactionManager;
    @Bean("springBatchError")
    public Job getJob() {
        return new JobBuilder("batchJobDemo", jobRepository)
                .incrementer(new RunIdIncrementer())
                .start(step1())
                .on("Rose").to(step2())
                .from(step1()).on("Lotus").to(step3())
                .end().build();
    }
    private Step step3() {
        return new StepBuilder("step2", jobRepository)
                .tasklet(((contribution, chunkContext) -> {
                    log.info("Executing Step " + contribution.getStepExecution().getStepName().toUpperCase());
                    return RepeatStatus.FINISHED;
                }), transactionManager)
                .build();
    }
    private Step step2() {
        return new StepBuilder("step3", jobRepository)
                .tasklet(((contribution, chunkContext) -> {
                    log.info("Executing Step " + contribution.getStepExecution().getStepName().toUpperCase());
                    return RepeatStatus.FINISHED;
                }), transactionManager)
                .build();
    }
   
   @Bean
   public Step step1() {
        return new StepBuilder("step1", jobRepository)
                .tasklet(((contribution, chunkContext) -> {
                    log.info("Executing step 1");
                    return RepeatStatus.FINISHED;
                }), transactionManager)
                .listener(new StepExec())
                .build();
    }
    static class StepExec implements StepExecutionListener {
        @Override
        public void beforeStep(StepExecution stepExecution) {
            log.info(String.format("Executing before Step Logic for %s", stepExecution.getStepName().toUpperCase()));
        }
        @Override
        public ExitStatus afterStep(StepExecution stepExecution) {
            String exitCode = new Random().nextBoolean() ? "Rose" : "Lotus";
            ExitStatus exitStatus = new ExitStatus(exitCode);
            log.info(String.format("Exit Status of %s is %s", stepExecution.getStepName().toUpperCase(), exitStatus.getExitCode()));
            return exitStatus;
        }
    }
}
```

**Comment by AJ198081** [comment] 2023-04-13 08:54
Thank you @acktsap - you are right, we need to declare all our Steps as Beans and have Spring auto inject them, this is especially true if we intending to refer to the same step multiple times in the same job, as otherwise if they are declared as 'methods' all Steps will be treated as different and hence the state transition will not work.

![image](https://user-images.githubusercontent.com/77644260/231707915-ddfbc9a9-7e9f-4455-96ce-50efa24439da.png)

**Closed** 2023-04-13 23:17 UTC
Labels: status: waiting-for-reporter, type: bug
