### ISSUE TITLE
A Problem about random value of step's StepName 

### ISSUE THREAD

**Issue by rikushin** [spring-projects/spring-batch#3677] opened 2020-03-09 05:09 UTC
I have a problem about random value of step's StepName.

I extend Spring Batch to call OS shell like .sh and .bat files from tasklet.
I also define a custom tag in xml configuration file to hold the information about OS shell.
But I don't define job and step tags in xml configuration file, and use BeanParser to just get 
a bean of TaskletStep. The xml configuration file is as below.
  `<beans>`
    `  <externalcommand="sampleExtJob.bat"/>` 
  `</beans>` 

I found that Spring Batch create and set the step name using a random value like below
        **(inner bean)#236c8f48**
It works fine until when I use spring Boot 2.2 and Spring Batch 4.2.0.

In Spring Batch 4.2, the Micrometer will collect metrics for job steps.
Micrometer use step name as a part of key to store metrics to MeterRegistry.
But because the step name is random, when I run the job repeatedly,
metrics data will increase continuously to cause a OutOfMemory.

So I try to set my own step name by defining job and step tags in xml configuration file, 
      `<beans>`
        `  <job xmlns="http://www.springframework.org/schema/batch" id="extJob" >`
		`   <step id="stepDefault">`
	           `   <tasklet ref="tasklet"/>`
		`  </step>`
	`</job>`
	`<bean id="tasklet" class="com.example.ExternalJobTasklet"/>`
        `<external command="sampleExtJob.bat"/>`
     `</beans>`
     
and I can get the correct step name from TaskletStep that created by BeanParser, 
but when step execution, the step name is overwritten by the random value as above.

Can spring batch not use random value to set step name for me?

**Comment by mminella** [comment] 2020-03-10 14:15
@rikushin Why did you `extend Spring Batch to call OS shell like .sh and .bat files from tasklet.`?  Spring Batch provides the [`SystemCommandTasklet`](https://docs.spring.io/spring-batch/docs/current/api/org/springframework/batch/core/step/tasklet/SystemCommandTasklet.html) so you could use that and use normal Spring Batch facilities and use "normal" step names.

Related to that, are you using a metrics store (aka are you using the functionality provided by Micrometer)?

**Comment by rikushin** [comment] 2020-03-12 02:00
I use Spring Batch from v1.1.4. At that time SystemCommandTasklet didn't exist. It is from V2 I think.
And my extended job works fine for me, so I don't change to SystemCommandTasklet.

By the way, What is the problem in my case ? I shouldn't create my own TaskletStep?
Where does the abnormal step name come from ?

**Comment by mminella** [comment] 2020-03-12 13:30
I'd need to see your code in more detail to reproduce the issue.  If you can provide a project that recreates it with a supported version of Spring Batch we can take a deeper look.  Otherwise, we'll close this issue.

**Comment by rikushin** [comment] 2020-03-19 06:39
Sorry ,I would like to evaluate the SystemCommandTasklet first.
After that if necessary, I will send you the code. 

By the way , Do you plan to develop a function to turn on or turn off the Micrometer's metrics 
collecting by a property in application.properties?  I think it is convenient function for user.

Thanks a lot

**Comment by benas** [comment] 2020-03-19 12:45
> Sorry ,I would like to evaluate the SystemCommandTasklet first.
> After that if necessary, I will send you the code.

ok that's fine. I'm closing this issue for now, if you manage to create a minimal project that reproduces the problem with Spring batch v4.2, we can re-open this issue.

> By the way , Do you plan to develop a function to turn on or turn off the Micrometer's metrics
> collecting by a property in application.properties?

No, there is no plan for that. We see metrics like logging: you can disable logs by configuring the logging library. Same for metrics, you can disable them by configuring the metrics library. For micrometer, you can use [meter filters](http://micrometer.io/docs/concepts#_meter_filters). Since by default spring batch stores metrics in the global registry, you can tell micrometer to ignore/deny batch metrics with: 

```java
Metrics.globalRegistry.config().meterFilter(MeterFilter.denyNameStartsWith("spring.batch"))
```

**Closed by benas** 2020-03-19 12:45 UTC
Labels: status: waiting-for-reporter
