### ISSUE TITLE
Multiple trationDelegate$BeanPostProcessorChecker Warnings Arise When Using Spring Boot 3.2.0

### ISSUE THREAD

**Issue by woosungkim0123** [spring-projects/spring-batch#4519] opened 2023-12-17 16:27 UTC
**Bug description**
When attempting to run a Batch process in Spring Boot 3.2.0, multiple BeanPostProcessorChecker warnings are being logged.

**Environment**
- Spring Batch version: 5.1
- Java version: 17, 21
- Database used (if applicable): H2
- Additional environment details: Spring Boot 3.2.0

**Steps to reproduce**
1. Configure an application using Spring Boot 3.2.0, Spring Batch 5.1, and H2 database.
2. Run the application.
3. BeanPostProcessorChecker warnings appear in the log.

**Expected behavior**
The application should initialize and run without any BeanPostProcessorChecker warnings.

**Minimal Complete Reproducible example**
The warnings that are being displayed have been documented in the README of the demo project.
[minimal example](https://github.com/woosungkim0123/batch-issue-demo)

**Comment by hpoettker** [comment] 2023-12-18 13:40
The issue is caused by the automatic bean exposure of `JobRegistryBeanPostProcessor` that has been introduced with #4245.

If you don't need the job beans to be registered with the `JobRegistry`, or use your own custom mechanism, you can disable it with code like this in one of your configuration classes:
```
@Bean
public static BeanDefinitionRegistryPostProcessor jobRegistryBeanPostProcessorRemover() {
  return registry -> registry.removeBeanDefinition("jobRegistryBeanPostProcessor");
}
```
The warnings should then disappear.

**Comment by woosungkim0123** [comment] 2023-12-19 14:29
thank you The issue has been resolved.

**Comment by pmsinclair** [comment] 2023-12-19 23:48
For applications with: @EnableBatchProcessing(modular = true)
This can actually cause: **DuplicateJobException**
This is due to both of these trying to register the same jobs:
1. JobRegistryBeanPostProcessor
2. AutomaticJobRegistrarBeanPostProcessor

**Comment by woosungkim0123** [comment] 2023-12-24 11:37
If this is what you intended or has been implemented in a new version, please feel free to close the issue.

**Comment by nightswimmings** [comment] 2024-01-09 10:30
The issue indicated by the warning actually affects the app. I have a  BeanPostProcessor that does not have any dependency and expects a certain bean autoconfigured and exposed by me in another section of the code, and as long as I don't add the removal mentioned by [hpoettker](https://github.com/hpoettker), my custompostprocessor cannot find my custom bean

**Comment by fmbenhassine** [comment] 2024-01-17 09:01
@woosungkim0123 Thank you for reporting this issue. This is not intentional, and those warning should be fixed. However, I think this issue is a duplicate of #4489, so I will close this one. Please follow the updates on #4489.

@pmsinclair That would be a bug! Please open a separate issue for that case. If you have a sample that reproduces the problem, please attach it in the issue.

@nightswimmings I don't see how the BPP added by Spring Batch could impact your custom BPP. If you think this is a side effect of #4245 , please open a separate issue with an example and we will address the problem.

Thank you all for your feedback on this!

**Closed by fmbenhassine** 2024-01-17 09:01 UTC
Labels: type: bug, in: core

**Comment by fmbenhassine** [comment] 2024-02-07 10:26
I just wanted to mention that the mechanism of using a BPP to populate the registry is problematic and will be fixed in 5.2 (#4547). In the meantime, the workaround for warnings in 5.1.x is to remove the `JobRegistryBeanPostProcessor` bean as described in https://github.com/spring-projects/spring-batch/issues/4519#issuecomment-1860530016. For those who need to populate the registry (when using the job operator for instance), a [JobRegistrySmartInitializingSingleton](https://docs.spring.io/spring-batch/reference/5.2-SNAPSHOT/job/advanced-meta-data.html#jobregistrysmartinitializingsingleton) will be available in 5.1.1 as a replacement of the BPP.

**Comment by PascalSchumacher** [comment] 2024-02-23 13:59
Sorry but I do not think this should be listed under "Bug fixes" in the 5.1.1 release notes, because this still occurs unless you use a workaround.

**Comment by fmbenhassine** [comment] 2024-02-26 14:17
@PascalSchumacher You are right. I see that I closed this issue as not planned (duplicate of #4489) but then I added it to the 5.1.1 milestone, which is incorrect. Apologies for the confusion caused by this. It is rather #4521 that should be in the change log in place of this issue. I updated the release notes accordingly. Thank you.

**Comment by PascalSchumacher** [comment] 2024-03-10 10:32
No problem. Thank you! 👍

**Comment by klopfdreh** [comment] 2024-07-31 07:00
> The issue is caused by the automatic bean exposure of `JobRegistryBeanPostProcessor` that has been introduced with #4245.
> 
> If you don't need the job beans to be registered with the `JobRegistry`, or use your own custom mechanism, you can disable it with code like this in one of your configuration classes:
> 
> ```
> @Bean
> public static BeanDefinitionRegistryPostProcessor jobRegistryBeanPostProcessorRemover() {
>   return registry -> registry.removeBeanDefinition("jobRegistryBeanPostProcessor");
> }
> ```
> 
> The warnings should then disappear.

For Spring Boot Native builds please consider this:
```java
    @Bean
    public static BeanDefinitionRegistryPostProcessor jobRegistryBeanPostProcessorRemover() {
        return registry -> {
            try {
                registry.removeBeanDefinition("jobRegistryBeanPostProcessor");
            } catch (NoSuchBeanDefinitionException e) {
                log.warn("Couldn't remove bean definition of 'jobRegistryBeanPostProcessor' - this might occur because of native builds.");
            }
        };
    }
```

As this error might occur:
```plain
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'jobRegistryBeanPostProcessor' available
```
