### ISSUE TITLE
When an error is thrown on process and an another error is thrown on write within a chunk during retry, the skippable item on write never processed. [BATCH-2818]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#797] opened 2019-04-24 15:18 UTC
**[dornwelt](https://jira.spring.io/secure/ViewProfile.jspa?name=dornwelt)** opened **[BATCH-2818](https://jira.spring.io/browse/BATCH-2818?redirect=false)** and commented

After the error [BATCH-2442](https://jira.spring.io/browse/BATCH-2442) has been fixed, the following error occurs: When an error is thrown on process and an another error is thrown on write within a chunk during retry, the write skip count is wrong and the onSkipInWrite - method on SkipListener never calls.

In attachment, the tescase testExceptionInProcessAndInWriteWithinChunk marked with "CUSTOM" and the possible solution that works for me.
* read 6 items (chunk = 3)
* while process last 3 items throw an error during process of item 4 and an error during write of item 6
* The write skip count is 0. Expected 1.
* The onSkipInWrite - method on SkipListener never calls
   

---

**Affects:** 4.1.0, 4.1.1, 4.1.2

**Attachments:**
- [FaultTolerantChunkProcessor.java](https://jira.spring.io/secure/attachment/26210/FaultTolerantChunkProcessor.java) (_20.89 kB_)
- [FaultTolerantStepIntegrationTests.java](https://jira.spring.io/secure/attachment/26209/FaultTolerantStepIntegrationTests.java) (_9.10 kB_)

**Comment by benas** [comment] 2020-02-28 09:19
This is a duplicate of #775. Indeed, there was a regression due to the fix of [BATCH-2442](https://jira.spring.io/browse/BATCH-2442) which has been fixed in #775.

> Affects: 4.1.0, 4.1.1, 4.1.2

The fix has been released in [4.0.4, 4.1.3 and 4.2.1](https://github.com/spring-projects/spring-batch/issues/775#issuecomment-566269029).

**Closed by benas** 2020-02-28 09:19 UTC
Labels: in: core, status: waiting-for-triage, type: bug
