### ISSUE TITLE
Spring Batch Remote Chunking parallel execution

### ISSUE THREAD

**Issue by akashsharma3030** [spring-projects/spring-batch#4272] opened 2023-01-09 13:01 UTC
**Expected Behavior**

It should be  possible to run multiple jobs in spring batch remote chunking 

**Current Behavior**

Currently it is not possible to run multiple jobs in spring batch remote chunking 

**Context**

We have a requirement to run multiple Spring batch remote chunking jobs

**Comment by fmbenhassine** [comment] 2023-01-12 11:23
Thank you for raising this issue. I believe it is a duplicate of https://github.com/spring-projects/spring-batch/issues/1372, where I added a comment on your comment.

Let's continue addressing the issue in #1372. Thank you.

**Closed** 2023-01-12 11:23 UTC
Labels: status: duplicate, status: declined
