### ISSUE TITLE
Accept and return java.time parameters?

### ISSUE THREAD

**Issue by PascalSchumacher** [spring-projects/spring-batch#3723] opened 2020-05-31 10:44 UTC
Currently classes like `JobParameters` and `JobExecution` only accept and return `java.util.Date`.

As `java.util.Date` has a lot of design flaws and should be avoided, what about adding methods accepting and returning a `java.time` class like `LocalDateTime`?

**Comment by benas** [comment] 2020-06-02 12:35
@PascalSchumacher I believe this is a duplicate of #1035 . Do you agree?

**Comment by PascalSchumacher** [comment] 2020-06-02 19:32
It has a wider scope than #1035, but I fine with closing this issue in favor of #1035. I did not find that issue before creating this one, sorry.

**Comment by benas** [comment] 2020-06-02 20:59
ok no worries. If it has a wider scope, please edit the title/description of this issue and narrow it to exclude what's already requested in #1035. Thank you upfront.

**Comment by mminella** [comment] 2020-09-11 13:50
For `JobParameters`, as @benas mentions, we already have an issue open for it. For `JobExecution` and `StepExecution` given that the vast majority of users do not manipulate these date other than formatting it, the cost of changing it outweighs the benefit for the few that would benefit from a more rich API. That coupled with the fact that `java.util.Date` has not been depricated by the JDK makes me think that we should not make this change.

Closing as a duplicate of #1035 where we can discuss the `JobParameters` use case.

**Closed by mminella** 2020-09-11 13:50 UTC
Labels: status: waiting-for-triage
