### ISSUE TITLE
Misleading chunkOrientedProcessing documetation

### ISSUE THREAD

**Issue by tomasz-belina-nes** [spring-projects/spring-batch#3833] opened 2021-01-19 10:04 UTC
According to this  chapter:
https://docs.spring.io/spring-batch/docs/4.2.x/reference/html/step.html#chunkOrientedProcessing
chunk is processed in a way that a reader reads one item and this item is passed directly into a processor. When chunk of data is fully processed whole chunks is passed to a writer. Reality is that whole chunk of data is red by the reader in the first place, after that every single item is passed into the processor and after that all items are passed into the writer.

**Comment by PawelGuz** [comment] 2021-01-19 10:07
This behavior allows to add new listener with method: afterChunkRead(List<T> redElements).

**Comment by benas** [comment] 2021-01-19 10:50
This is a duplicate of #1179 and #1629 .

**Closed by benas** 2021-01-19 10:50 UTC
