### ISSUE TITLE
java.lang.NoSuchFieldError: BLOCK_UNSAFE_POLYMORPHIC_BASE_TYPES on deploying application migrated from spring boot version 2.2.x to 2.6.6

### ISSUE THREAD

**Issue by sr9112** [spring-projects/spring-batch#4091] opened 2022-04-05 23:09 UTC
Afte upgrading spring job apps to use spring boot library v2.6.6 with spring batch v4.3.5,below error is seen while deploying the application on the server with JDK8.

_Caused by: java.lang.NoSuchFieldError: BLOCK_UNSAFE_POLYMORPHIC_BASE_TYPES
    at org.springframework.batch.core.repository.dao.Jackson2ExecutionContextStringSerializer.<init>(Jackson2ExecutionContextStringSerializer.java:119)
    at org.springframework.batch.core.repository.support.JobRepositoryFactoryBean.afterPropertiesSet(JobRepositoryFactoryBean.java:192)
    at org.springframework.boot.autoconfigure.batch.BasicBatchConfigurer.createJobRepository(BasicBatchConfigurer.java:133)
    at org.springframework.boot.autoconfigure.batch.BasicBatchConfigurer.initialize(BasicBatchConfigurer.java:101)
    at org.springframework.boot.autoconfigure.batch.BasicBatchConfigurer.afterPropertiesSet(BasicBatchConfigurer.java:95)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1847)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784)_

**Steps to reproduce**
Upgrade to spring boot application using spring batch jobs to spring boot starter v2.6.6

Check the below link for reported issue -
(https://stackoverflow.com/questions/65607909/spring-batch-2-4-1-wildfly-20-final-java-lang-nosuchfielderror-block-unsafe)

**Comment by benas** [comment] 2022-04-06 08:41
From which version are you upgrading? What is the `jackson-databind` version you have in your classpath?

**Comment by sr9112** [comment] 2022-04-06 10:26
Migrtaing from 2.2.5 to 2.6.6. The jackson-bind library version seen in the build is v2.13.2.2 when upgrading to spring boot v2.6.6. Also, tried upgrading to spring boot v2.5.12 which has  jackson-bind library version 2.12.6.1. 

In both the cases same error is seen. Error is seen when jobRepository is being initialized during job autoconfiguration.

**Comment by benas** [comment] 2022-04-07 09:21
Thank you for your feedback. You seem to have a (manual) dependency management issue. With boot 2.2.5, you get batch 4.2.1 and jackson 2.10.2. In this case the [execution context serializer](https://github.com/spring-projects/spring-batch/blob/4.2.x/spring-batch-core/src/main/java/org/springframework/batch/core/repository/dao/Jackson2ExecutionContextStringSerializer.java) does not use  `BLOCK_UNSAFE_POLYMORPHIC_BASE_TYPES` and the error does not happen. You can see that in the attached project.

With boot 2.6.6, you get batch 4.3.5 and jackson 2.13.2. In this case, the [execution context serializer](https://github.com/spring-projects/spring-batch/blob/4.3.x/spring-batch-core/src/main/java/org/springframework/batch/core/repository/dao/Jackson2ExecutionContextStringSerializer.java) does use `BLOCK_UNSAFE_POLYMORPHIC_BASE_TYPES` which is present in jackson and the error you reported does not happen neither.

So you should be overriding some versions manually. I am not able to reproduce the issue, see the attached project which lets boot manage dependencies. I'm closing this issue for now, but if you can provide a minimal reproducer, I can dig deeper. Thank you.

Minimal example: [demo4091.zip](https://github.com/spring-projects/spring-batch/files/8441407/demo4091.zip)

**Closed by benas** 2022-04-07 09:21 UTC
Labels: status: waiting-for-reporter, type: bug

**Comment by KaviAKKAJ** [comment] 2023-09-13 16:03
Hi,  I am using spring batch 4.3.8 and using jackson-databind 2.13.4.2 version.
Facing same issue. Can you please suggest to resolve this issue?
