### ISSUE TITLE
Disable single item writing mode after skippable ItemWriter throw exception when the chunk size is 1

### ISSUE THREAD

**Issue by kenchanmc** [spring-projects/spring-batch#3822] opened 2020-12-27 21:31 UTC
I understand from [this](https://stackoverflow.com/a/50471346/339637) if an skip is configured and if an ItemWriter throw an exception  , it will then go to the "single-item" writing mode simply because we do not know which item in that chunk causes the exception.

But if  the chunk size is 1 , then we must 100% sure it is the only item in that chunk cause error , and so does it make sense to still go to the "single-item" writing mode in this case ? The current end result is that it will process the failure items two times even I configure `AlwaysSkipItemSkipPolicy` which sounds awkward if the chunk size is 1.

I am happy to provide a PR if you think it makes sense.

**Comment by benas** [comment] 2021-01-04 13:47
@kenchanmc I believe this is a duplicate of #2064. Do you agree?

**Comment by kenchanmc** [comment] 2021-01-06 10:15
Yes. I agree. Let me close this issue and refer to #2064 .
Thanks.

**Closed** 2021-01-06 10:14 UTC
Labels: status: waiting-for-reporter
