### ISSUE TITLE
Create table BATCH_JOB_EXECUTION throws SqlSyntaxErrorException with db2

### ISSUE THREAD

**Issue by omheni** [spring-projects/spring-batch#4000] opened 2021-09-13 10:07 UTC
**Expected Behavior**

Create all the tables( 6 tables) found in the **schema-db2.sql** script.

**Current Behavior**
Create Only the first table and skip the creation of the 5 others, following an exception thrown when creating the table **BATCH_JOB_EXECUTION**

_SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=,;N VARCHAR(2500) null;<references_spec>...._

In fact	JOB_CONFIGURATION_LOCATION VARCHAR(2500) **NULL**, cause a problem.

**Context**
Here is the corrected script:
 CREATE TABLE BATCH_JOB_EXECUTION  (
	JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT  ,
	JOB_INSTANCE_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL ,
	END_TIME TIMESTAMP DEFAULT NULL ,
	STATUS VARCHAR(10) ,
	EXIT_CODE VARCHAR(2500) ,
	EXIT_MESSAGE VARCHAR(2500) ,
	LAST_UPDATED TIMESTAMP,
	JOB_CONFIGURATION_LOCATION VARCHAR(2500) DEFAULT NULL,
	constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
	references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

**Comment by benas** [comment] 2021-09-13 17:21
Closing this as duplicate of #4001 .

**Closed by benas** 2021-09-13 17:21 UTC
Labels: status: waiting-for-triage, type: feature
