### ISSUE TITLE
Error creating bean with name 'scopedTarget.initialStep': Scope 'job' is not active for the current thread

### ISSUE THREAD

**Issue by itatkakaxi2** [spring-projects/spring-batch#3640] opened 2020-01-01 12:24 UTC
When I try to configure a job using the Conditional Flow API such as the following:
```
   @Bean(FILE_JOB)
    public Job generalFileJob(@Qualifier(INITIAL_STEP) Step initialStep, 
            @Qualifier(DOWNLOAD_STEP) Step downloadStep,
            @Qualifier(VALIDATION_STEP) Step validationStep, 
            @Qualifier(SEND_MSG_STEP) Step sendMsgStep,
            CommonJobListener jobListener) {

        return this.jobBuilderFactory.get(FILE_JOB)
                .listener(jobListener)
                .start(initialStep).on(COMPLETE_WITH_EMPTY).end()
                .from(initialStep).on(COMPLETE).to(downloadStep)
                .on(COMPLETE).to(validationStep)
                .on(COMPLETE).to(sendMsgStep)
                .end()
                .build();
    }

    @JobScope
    @Bean(INITIAL_STEP)
    public Step initialStep(QueryFraudFileTasklet queryFraudFileTasklet) {
        return this.stepBuilderFactory.get(INITIAL_STEP)
                .tasklet(queryFraudFileTasklet)
                .allowStartIfComplete(true)
                .listener(QueryFraudFileListener.INSTANCE)
                .build();
    }
```
There will be exception thrown from this process with the following exception stack:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.initialStep': Scope 'job' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No context holder available for job scope
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:365)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:193)
	at com.sun.proxy.$Proxy107.getName(Unknown Source)
	at org.springframework.batch.core.job.builder.FlowBuilder.createState(FlowBuilder.java:282)
	at org.springframework.batch.core.job.builder.FlowBuilder.doStart(FlowBuilder.java:265)
	at org.springframework.batch.core.job.builder.FlowBuilder.start(FlowBuilder.java:122)
	at org.springframework.batch.core.job.builder.JobFlowBuilder.<init>(JobFlowBuilder.java:39)
	at org.springframework.batch.core.job.builder.SimpleJobBuilder.on(SimpleJobBuilder.java:91)
	at com.mastercard.cnswitch.risk.batch.fraudfile.configuration.FraudFileJobConfiguration.fraudFileJob(FraudFileJobConfiguration.java:55)
	at com.mastercard.cnswitch.risk.batch.fraudfile.configuration.FraudFileJobConfiguration$$EnhancerBySpringCGLIB$$a113d60d.CGLIB$fraudFileJob$2(<generated>)
	at com.mastercard.cnswitch.risk.batch.fraudfile.configuration.FraudFileJobConfiguration$$EnhancerBySpringCGLIB$$a113d60d$$FastClassBySpringCGLIB$$4e33f171.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.mastercard.cnswitch.risk.batch.fraudfile.configuration.FraudFileJobConfiguration$$EnhancerBySpringCGLIB$$a113d60d.fraudFileJob(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 20 common frames omitted
Caused by: java.lang.IllegalStateException: No context holder available for job scope
	at org.springframework.batch.core.scope.JobScope.getContext(JobScope.java:159)
	at org.springframework.batch.core.scope.JobScope.get(JobScope.java:92)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:353)
	... 40 common frames omitted
```
When to iterate the stack trace I find that the following method which tries to invoke bean's getName method and this will trigger the initialization of the real step bean. Because the step bean is in job scope but there's no job execution created so the exception is thrown.
```
private State createState(Object input) {
        State result;
        if (input instanceof Step) {
            if (!this.states.containsKey(input)) {
                Step step = (Step)input;
                this.states.put(input, new StepState(this.prefix + step.getName(), step));
            }

            result = (State)this.states.get(input);
        } else if (input instanceof JobExecutionDecider) {
            if (!this.states.containsKey(input)) {
                this.states.put(input, new DecisionState((JobExecutionDecider)input, this.prefix + "decision" + this.decisionCounter++));
            }

            result = (State)this.states.get(input);
        } else {
            if (!(input instanceof Flow)) {
                throw new FlowBuilderException("No state can be created for: " + input);
            }

            if (!this.states.containsKey(input)) {
                this.states.put(input, new FlowState((Flow)input, this.prefix + ((Flow)input).getName()));
            }

            result = (State)this.states.get(input);
        }

        this.dirty = true;
        return result;
    }
```
So I think this is the issue to process.

**Comment by itatkakaxi2** [comment] 2020-01-01 12:32
Also, the version used is Spring Batch 4.2.0

**Comment by benas** [comment] 2020-02-28 22:27
This is a duplicate of https://github.com/spring-projects/spring-batch/issues/857.

**Closed by benas** 2020-02-28 22:27 UTC
Labels: status: waiting-for-triage
