### ISSUE TITLE
BATCH_JOB_SEQ never initialize [BATCH-2799]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#801] opened 2019-03-17 07:11 UTC
**[John Cao](https://jira.spring.io/secure/ViewProfile.jspa?name=jhcao23)** opened **[BATCH-2799](https://jira.spring.io/browse/BATCH-2799?redirect=false)** and commented

I have set spring.batch.initialize-schema = always;

every time when I start my app, without any Jobs start, batch-mysql.sql last line never run; however, the other batch sequence tables is working properly. This is so weird that the application always run into Exception, but when I manually run the last line, the exception (duplicate job id 0) is away.

```java
INSERT INTO BATCH_JOB_SEQ (ID, UNIQUE_KEY) select * from (select 0 as ID, '0' as UNIQUE_KEY) as tmp where not exists(select * from BATCH_JOB_SEQ)
```

---

**Affects:** 4.1.1

**Comment by fmbenhassine** [comment] 2024-05-02 09:23
I was not able to reproduce this issue with Spring Boot 3.2.5, see attached sample. The last line of the script is executed and the job runs without errors.

I am closing this issue as it seems outdated, but if anyone still has the problem, please add a comment and we will dig further.

[demo.zip](https://github.com/spring-projects/spring-batch/files/15186208/demo.zip)

**Closed by fmbenhassine** 2024-05-02 09:23 UTC
Labels: status: waiting-for-triage, type: bug, in: core, related-to: ddl-scripts
