### ISSUE TITLE
Modify schema-*.sql add IF NOT EXISTS to Create tables

### ISSUE THREAD

**Issue by walidnsir** [spring-projects/spring-batch#4468] opened 2023-10-18 14:46 UTC
Hello,

We used the last stable version 5.0.3
We have in our database same error like ERROR: relation "batch_job_instance/..." already exists" every time when is running
We khow that is not blocking but we suggest to change yours dll sql file used to create table with command 
CREATE table IF NOT EXISTS

best regards

**Comment by fmbenhassine** [comment] 2023-10-24 13:20
Closing this as duplicate of #1855.

**Closed as not planned by fmbenhassine** 2023-10-24 13:20 UTC
Labels: status: duplicate
