### ISSUE TITLE
Allow ItemListenerSupport inside SimpleStepBuilder#listener(...) [BATCH-2829]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#785] opened 2019-07-09 09:54 UTC
**[Sam-Kruglov](https://jira.spring.io/secure/ViewProfile.jspa?name=sam-kruglov)** opened **[BATCH-2829](https://jira.spring.io/browse/BATCH-2829?redirect=false)** and commented

If I want to define a global exception handler using `ItemListenerSupport` then I have to cast it in step factory like this:

```
stepBuilderFactory.get("myStep")
                .chunk<Long, Booelan>(1)
                .reader(reader)
                .processor(processor)
                .listener((ItemProcessListener<Object, Object>) errorHandler)
```

And I checked, that it does listen to all 3 (reader, processor, writer)

---

**Affects:** 4.1.2

**Comment by fmbenhassine** [comment] 2024-05-03 08:55
Closing this as duplicate of #1141

**Closed by fmbenhassine** 2024-05-03 08:55 UTC
Labels: status: waiting-for-triage, type: enhancement
