### ISSUE TITLE
i get an error when creating a graalvm native image 

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-batch#4294] opened 2023-02-11 01:20 UTC
i get an error about a proxy being created for `JobOperator` when creating a GraalVM native image with the following java code and build file:

## build file 

Here's the build file:

```groovy

plugins {
	id 'java'
	id 'org.springframework.boot' version '3.0.2'
	id 'io.spring.dependency-management' version '1.1.0'
	id 'org.graalvm.buildtools.native' version '0.9.18'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-batch'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	implementation 'org.postgresql:postgresql'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.batch:spring-batch-test'
}

tasks.named('test') {
	useJUnitPlatform()
}
```

## Java code

```java
package com.example.batch;

import org.springframework.aot.hint.RuntimeHints;
import org.springframework.aot.hint.RuntimeHintsRegistrar;
import org.springframework.batch.core.Job;
import org.springframework.batch.core.JobParametersBuilder;
import org.springframework.batch.core.Step;
import org.springframework.batch.core.configuration.annotation.StepScope;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.launch.JobLauncher;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.core.step.tasklet.Tasklet;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ImportRuntimeHints;
import org.springframework.transaction.PlatformTransactionManager;

import java.util.UUID;

@SpringBootApplication
public class BatchApplication {

  
    public static void main(String[] args) {
        SpringApplication.run(BatchApplication.class, args);
    }

    @Bean
    ApplicationRunner runner(JobLauncher jobLauncher, Job job) {
        return args -> {
            var jobParameters = new JobParametersBuilder()
                    .addString("uuid", UUID.randomUUID().toString())
                    .toJobParameters();
            var run = jobLauncher.run(job, jobParameters);
            var instanceId = run.getJobInstance().getInstanceId();
            System.out.println("instanceId: " + instanceId);
        };
    }

    @Bean
    @StepScope
    Tasklet tasklet(@Value("#{jobParameters['uuid']}") String uuid) {
        return (contribution, context) -> {
            System.out.println("hello, world! the UUID is " + uuid);
            return RepeatStatus.FINISHED;
        };
    }

    @Bean
    Job job(JobRepository jobRepository, Step step) {
        return new JobBuilder("job", jobRepository)
                .start(step) //
                .build();
    }

    @Bean
    Step step1(JobRepository jobRepository, Tasklet tasklet, PlatformTransactionManager transactionManager) {
        return new StepBuilder("step1", jobRepository) //
                .tasklet(tasklet, transactionManager) //
                .build();
    }
}

```

It runs fine on the JRE. And obviously, if I register the hint, it works fine too:

```java
 @ImportRuntimeHints(Hints.class) 
```

and

```java
    static class Hints implements RuntimeHintsRegistrar {

        @Override
        public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
            hints.proxies().registerJdkProxy(
                    org.springframework.batch.core.launch.JobOperator.class,
                    org.springframework.aop.SpringProxy.class, org.springframework.aop.framework.Advised.class, org.springframework.core.DecoratingProxy.class
            );
        }
    }

```

**Comment by hpoettker** [comment] 2023-02-11 12:32
This is a duplicate of #4248.

A heads-up in case you want to run native tests with `@SpringBatchTest`: #4286

**Comment by fmbenhassine** [comment] 2023-02-13 11:03
Thank you for reporting this, Josh!

As mentioned by @hpoettker, this has been already reported in #4248. The fix will be included in the upcoming 5.0.1 (and is already available in the snapshots).

@hpoettker Thank you for the follow up!

**Closed by fmbenhassine** 2023-02-13 11:03 UTC
Labels: status: waiting-for-triage, type: bug
