### ISSUE TITLE
girdsize class cast exception

### ISSUE THREAD

**Issue by EthanKk** [spring-projects/spring-batch#4219] opened 2022-10-24 07:24 UTC
**Bug description**
We got a ClassCastException when using a partition step. The gird size I set is 10, so the ExecutionContext persist it to db as Integer. But when i restart this failed partition step, something wrong happened:

SimpleStepExecutionSplitter.getContexts:
```
int splitSize = (int) context.getLong(key, gridSize);
context.putLong(key, splitSize);
```
Why not just use getInteger at this place?

**Environment**
Spring Batch version: 4.3.6
database version: mysql 5.7

**Comment by fmbenhassine** [comment] 2022-10-24 07:28
Thank you for opening this issue. Is this the same issue as reported in https://github.com/spring-projects/spring-batch/issues/3771?

**Comment by EthanKk** [comment] 2022-10-24 07:37
Yes. Is there any good solution now?

**Comment by fmbenhassine** [comment] 2022-10-24 07:46
> Yes. 

Thank you for the feedback. I will close this as a duplicate.

As for the status, please see https://github.com/spring-projects/spring-batch/issues/3771#issuecomment-920942368 where I was not able to reproduce the issue with the default serializer provided by Spring Batch. So the issue seems related to using a custom serializer. Please add a comment in #3771 if you need further support on this.

**Closed by fmbenhassine** 2022-10-24 07:46 UTC
Labels: status: waiting-for-reporter, type: bug
