### ISSUE TITLE
Jackson2ExecutionContextStringSerializer breaks backward compatibility

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-batch#3826] opened 2021-01-05 04:26 UTC
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [map type; class java.util.HashMap, [simple type, class java.lang.String] -> [simple type, class java.lang.Object]]: missing type id property '@class'
 at [Source: (ByteArrayInputStream); line: 1, column: 2]
```
data is generated by spring-batch 4.2.x
```
mysql> select * from BATCH_JOB_EXECUTION_CONTEXT;
+------------------+---------------+--------------------+
| JOB_EXECUTION_ID | SHORT_CONTEXT | SERIALIZED_CONTEXT |
+------------------+---------------+--------------------+
|                1 | {}            | NULL               |
|                2 | {}            | NULL               |
|                3 | {}            | NULL               |

```
Caused by DefaultTyping is introduced by https://github.com/spring-projects/spring-batch/commit/9a79b4572d0aa4bec38fe90957c850920b7f9cea, since the json is generated by spring-batch itself, attacker cannot tamper it, I think it's important to keep compatibility over security.

**Comment by benas** [comment] 2021-01-05 12:45
Closing this as duplicate of #3732 

> I think it's important to keep compatibility over security.

Please check Michel's [comment here](https://github.com/spring-projects/spring-batch/issues/3732#issuecomment-647745021).

**Closed by benas** 2021-01-05 12:45 UTC
Labels: status: waiting-for-triage, type: bug
