### ISSUE TITLE
Change mysql datatime type to datetime(6)

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-batch#3690] opened 2020-04-02 02:36 UTC
MySQL has [fractional seconds support](https://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html) since 5.6, I think new version of `spring-batch` should follow up.

**Comment by benas** [comment] 2020-04-02 07:40
Thank you for opening this issue. We are [aware](https://github.com/spring-projects/spring-batch/issues/2202#issuecomment-574237266) of that, and the fix is planned for next release 4.3.

I'm closing this as duplicate of #2202 .

**Closed by benas** 2020-04-02 07:40 UTC
